spring.application.name=demo

spring.datasource.url=jdbc:mariadb://localhost:3306/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.jpa.hibernate.ddl-auto=update

# 스프링 AI는 OpenAI SDK 호환성을 위해 OPENAI_API_KEY도 지원하므로 다음 설정은 없어도 됨.
spring.ai.openai.api-key=${OPENAI_API_KEY}
