server.port=8088
spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}

# 주문 목록 알려 줘.
spring.ai.mcp.client.streamable-http.connections.product-order-server.url=http://localhost:8080

# 지금 몇시야?
spring.ai.mcp.client.stdio.connections.datetime.command=java.exe
spring.ai.mcp.client.stdio.connections.datetime.args=-jar,D:/hackers/workspace/datetime-mcp-server.jar
