server.port=8088
spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.mcp.client.streamable-http.connections.product-order-server.url=http://localhost:8080

# npx.cmd in Windows, npx in Linux and MacOS
spring.ai.mcp.client.stdio.connections.notion.command=npx.cmd
spring.ai.mcp.client.stdio.connections.notion.args=-y,@notionhq/notion-mcp-server
spring.ai.mcp.client.stdio.connections.notion.env.NOTION_TOKEN=${NOTION_TOKEN}