spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}

# 주문 목록 알려 줘.
spring.ai.mcp.client.streamable-http.connections.product-order-server.url=http://localhost:8090
# 스프링부트에 대해 조사해서 D:/hackers/workspace/springboot-summary.txt로 저장해 줘.
# 지금 몇시야?
spring.ai.mcp.client.stdio.connections.datetime.command=java.exe
spring.ai.mcp.client.stdio.connections.datetime.args=-jar,D:/hackers/workspace/filesystem-mcp-server.jar

# 스프링 AI에 대해 요약하여 "스프링 AI 요약"이라는 제목의 페이지 작성해 줘.
# 회의 내용 요약해서 회의록-{날짜} 제목의 페이지 작성해 줘.
spring.ai.mcp.client.stdio.connections.notion.command=npx.cmd
spring.ai.mcp.client.stdio.connections.notion.args=-y,@notionhq/notion-mcp-server
spring.ai.mcp.client.stdio.connections.notion.env.NOTION_TOKEN=${NOTION_TOKEN}