spring.application.name=demo

spring.ai.openai.api-key=${OPENAI_API_KEY}

# 스프링 AI에 대해 요약하여 "스프링 AI 요약"이라는 제목의 페이지 작성해 줘.
spring.ai.mcp.client.stdio.connections.notion.command=npx.cmd
spring.ai.mcp.client.stdio.connections.notion.args=-y,@notionhq/notion-mcp-server
spring.ai.mcp.client.stdio.connections.notion.env.NOTION_TOKEN=${NOTION_TOKEN}

# 스프링 AI에 대해 요약하여 spring-ai-summary.txt 파일로 저장해 줘.
spring.ai.mcp.client.stdio.connections.filesystem.command=npx.cmd
spring.ai.mcp.client.stdio.connections.filesystem.args=-y,@modelcontextprotocol/server-filesystem,D:/hackers/workspace

# https://docs.spring.io/spring-ai/reference/api/mcp/mcp-annotations-overview.html 내용을 읽고 MCP 지원 기능을 정리해 줘.
spring.ai.mcp.client.stdio.connections.fetchserver.command=npx.cmd
spring.ai.mcp.client.stdio.connections.fetchserver.args=-y,mcp-fetch-server

# 오늘 서울 날씨 알려 줘.
spring.ai.mcp.client.stdio.connections.weather.command=npx.cmd
spring.ai.mcp.client.stdio.connections.weather.args=-y,open-meteo-mcp-server

# 네이버 홈 화면 캡쳐해서 파일로 저장해 줘.
# 네이버에서 AI 관련 뉴스 상위 5개 제목을 알려 줘.
spring.ai.mcp.client.stdio.connections.playwright.command=npx.cmd
spring.ai.mcp.client.stdio.connections.playwright.args=-y,@playwright/mcp,--output-dir,D:/hackers/workspace

# 지금 몇시야?
spring.ai.mcp.client.stdio.connections.datetime.command=node
spring.ai.mcp.client.stdio.connections.datetime.args=D:/hackers/mcp/datetime-mcp-server/index.js

