spring.application.name=demo

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.mcp.client.stdio.connections.notion.command=npx.cmd
spring.ai.mcp.client.stdio.connections.notion.args=-y,@notionhq/notion-mcp-server
spring.ai.mcp.client.stdio.connections.notion.env.NOTION_TOKEN=${NOTION_TOKEN}

spring.ai.mcp.client.stdio.connections.filesystem.command=npx.cmd
spring.ai.mcp.client.stdio.connections.filesystem.args=-y,@modelcontextprotocol/server-filesystem,D:/hackers/workspace

spring.ai.mcp.client.stdio.connections.fetchserver.command=npx.cmd
spring.ai.mcp.client.stdio.connections.fetchserver.args=-y,mcp-fetch-server

